# Generated by Django 3.2.20 on 2023-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=50)),
                ('COR', models.CharField(max_length=50)),
                ('MATERIAL', models.CharField(max_length=30)),
                ('VALOR', models.IntegerField()),
            ],
        ),
    ]
